name: Deploy

on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: './dist'
      - uses: actions/deploy-pages@v4